### ISSUE TITLE
try: except:?

### ISSUE THREAD

**Issue by ganwell** [edk0/spy#3]
spy is a great tool, thanks.

I wonder if I can do something like `try: pipe[3]; except: pass`. I usually filter out anything that raises an exception, but currently I have an example where filtering out is a lot of work.

**Comment by edk0** [comment]
Hmm. It'd be quite hard to support that as written, but a decorator (-t/--try?) would be easy. It'd feel a bit more spy-like to add a "run in a context manager" decorator, but I can't really see any other uses for it, and `--foo contextlib.suppress(BaseException)` is a bit of a mouthful.

**Comment by ganwell** [comment]
Yes, I was thinking of `-t/--try`. Maybe `spy.ignore(pipe[3])`, but I find it a bit strange that `ignore()` has to pass the result from the expression through and unfortunately `spy.try` is not possible because it is a reserved word.

**Comment by edk0** [comment]
fixed by #4
